/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import estructuras.App;
import estructuras.Ciudad;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jose Gabriel
 */

//gestiona todo lo relacionado con la ventana principal y el visualizador
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    
    //se crean los paneles que se empelarán
    static IniciarSimulacion pnl_iniciarSimulacion;
    EditarMapa pnl_editarMapa;
    CargarArchivo pnl_cargarArchivo;
    GuardarArchivo pnl_guardarArchivo;
    static CardLayout vista;
    static CardLayout vista_grafo;
    
    static App app;
    public PrincipalFrame() {
        initComponents();
        vista=(CardLayout)vistaPrincipal.getLayout();
        vista_grafo=(CardLayout)visualizador.getLayout();
        App.iniciarGrafo();
        pnl_iniciarSimulacion = new IniciarSimulacion();
        pnl_editarMapa= new EditarMapa();
        pnl_guardarArchivo=new GuardarArchivo();
        pnl_cargarArchivo=new CargarArchivo();
        
    }
    
    //se emplea para actualizar los combobox de las ciudades
    public void actualizarComboboxCiudades(){
    pnl_editarMapa.actualizarComboboxCiudades();    
    }
    
    //permite actualizar el visualizador del mapa
    public  void actualizarVisor(){
        App.cargarVisualizador();
        visualizador.add(App.verGrafo(),"vista_pequeña");
        vista_grafo.show(visualizador, "vista_pequeña");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boton_iniciarSimulacion = new javax.swing.JToggleButton();
        boton_editarMapa = new javax.swing.JToggleButton();
        cargarMapa = new javax.swing.JToggleButton();
        guardarMapa = new javax.swing.JToggleButton();
        verGrafo = new javax.swing.JToggleButton();
        eliminarMapa = new javax.swing.JToggleButton();
        vistaPrincipal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        visualizador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");

        boton_iniciarSimulacion.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(boton_iniciarSimulacion);
        boton_iniciarSimulacion.setForeground(new java.awt.Color(0, 0, 0));
        boton_iniciarSimulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hormiga_pequeño.png"))); // NOI18N
        boton_iniciarSimulacion.setText("Iniciar Simulación");
        boton_iniciarSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_iniciarSimulacionActionPerformed(evt);
            }
        });

        boton_editarMapa.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(boton_editarMapa);
        boton_editarMapa.setForeground(new java.awt.Color(0, 0, 0));
        boton_editarMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorrido.png"))); // NOI18N
        boton_editarMapa.setText("Editar Recorrido");
        boton_editarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_editarMapaActionPerformed(evt);
            }
        });

        cargarMapa.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(cargarMapa);
        cargarMapa.setForeground(new java.awt.Color(0, 0, 0));
        cargarMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carga_pequeño.png"))); // NOI18N
        cargarMapa.setText("Cargar Mapa");
        cargarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarMapaActionPerformed(evt);
            }
        });

        guardarMapa.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(guardarMapa);
        guardarMapa.setForeground(new java.awt.Color(0, 0, 0));
        guardarMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save_pequeño.png"))); // NOI18N
        guardarMapa.setText("Guardar Mapa");
        guardarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMapaActionPerformed(evt);
            }
        });

        verGrafo.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(verGrafo);
        verGrafo.setForeground(new java.awt.Color(0, 0, 0));
        verGrafo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mapa_pequeño.png"))); // NOI18N
        verGrafo.setText("Visualizar Mapa");
        verGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verGrafoActionPerformed(evt);
            }
        });

        eliminarMapa.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(eliminarMapa);
        eliminarMapa.setForeground(new java.awt.Color(0, 0, 0));
        eliminarMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        eliminarMapa.setText("Eliminar Mapa");
        eliminarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guardarMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cargarMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton_iniciarSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton_editarMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verGrafo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminarMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_iniciarSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_editarMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargarMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardarMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        vistaPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        vistaPrincipal.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mapa de Navegación");

        jPanel4.setBackground(new java.awt.Color(31, 31, 31));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Leyenda Final.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
        );

        visualizador.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(visualizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(visualizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_iniciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_iniciarSimulacionActionPerformed
        
        //se muestra el panel de simulacion
        vistaPrincipal.add(pnl_iniciarSimulacion,"simulacion");
        vista.show(vistaPrincipal, "simulacion");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_boton_iniciarSimulacionActionPerformed

    private void boton_editarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_editarMapaActionPerformed
        //se muestra el panel de edición de mapa
        vistaPrincipal.add(pnl_editarMapa,"mapa");
        vista.show(vistaPrincipal, "mapa");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_boton_editarMapaActionPerformed

    private void verGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verGrafoActionPerformed
        //se muestra el mapa más grande
        App.cargarVisualizador();
        vistaPrincipal.add(App.verGrafo(),"visual");
        vista.show(vistaPrincipal, "visual");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_verGrafoActionPerformed

    private void eliminarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMapaActionPerformed
        //se elimina el grafo actual
        Ciudad.autoincremental=0;
        App.iniciarGrafo();
        App.cargarVisualizador();
        visualizador.add(App.verGrafo(),"vista_pequeña");
        vista_grafo.show(visualizador, "vista_pequeña");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        pnl_iniciarSimulacion = new IniciarSimulacion();
        pnl_editarMapa.actualizarComboboxCiudades();
    }//GEN-LAST:event_eliminarMapaActionPerformed

    private void cargarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarMapaActionPerformed
        //se carga un mapa anteriormente guardado
        App.cargarGrafo(this);
        pnl_editarMapa.actualizarComboboxCiudades();  
        vistaPrincipal.add(pnl_cargarArchivo,"cargar");
        vista.show(vistaPrincipal, "cargar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        pnl_editarMapa.actualizarMiniGrafo();
    }//GEN-LAST:event_cargarMapaActionPerformed

    private void guardarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMapaActionPerformed
        //se guarda un mapa
        App.guardarGrafo(this);
        vistaPrincipal.add(pnl_guardarArchivo,"guardar");
        vista.show(vistaPrincipal, "guardar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_guardarMapaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToggleButton boton_editarMapa;
    private javax.swing.JToggleButton boton_iniciarSimulacion;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JToggleButton cargarMapa;
    public static javax.swing.JToggleButton eliminarMapa;
    public static javax.swing.JToggleButton guardarMapa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JToggleButton verGrafo;
    public static javax.swing.JPanel vistaPrincipal;
    public static javax.swing.JPanel visualizador;
    // End of variables declaration//GEN-END:variables
}
