/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

import static Frames.PrincipalFrame.vista_grafo;
import static Frames.PrincipalFrame.visualizador;
import estructuras.App;
import javax.swing.SwingUtilities;

/**
 *
 * @author Leonardo
 */
public class Visualizador_Grafo extends javax.swing.JPanel {

    /**
     * Creates new form Visualizador_Grafo
     */
    public Visualizador_Grafo() {
        initComponents();
    }
    public void actualizarVisor(){
        App.cargarVisualizador();
        visualizador.add(App.verGrafo(),"vista_pequeña");
        vista_grafo.show(visualizador, "vista_pequeña");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
